
#Название проекта
name: booking-system

services:

  #PostgreSQL
  db:
    image: postgres:17-alpine3.22
    container_name: booking-system-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6432:5432"
    volumes:
      - booking-system-db-volume:/var/lib/postgresql/data
      - ./booking-system-backend/src/main/resources/static/data:/tmp/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  
  minio:
    image: minio/minio
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-volume:/data
    command: server /data --console-address ":9001"
    #TODO healthcheck

  redis:
    image: redis:8.6.3
    container_name: redis-storage
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    command: redis-server --appendonly yes
    #TODO healthcheck

volumes:
  booking-system-db-volume:
  minio-volume:
  redis-volume: